# Generated by Django 4.1.6 on 2023-02-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user_name',
        ),
    ]
