# Generated by Django 4.1.6 on 2023-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_address_user_email_remove_address_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
