# Generated by Django 4.1.6 on 2023-02-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.IntegerField(choices=[(1, 'inactive'), (1, 'active')], default=0),
        ),
    ]
