# Generated by Django 4.1.6 on 2023-02-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_address_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
