# Generated by Django 4.1.6 on 2023-02-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_address_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_name',
        ),
    ]
