# Generated by Django 4.1.6 on 2023-02-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_image_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('status', '-updated')},
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('ready_to_send', 'Ready to send'), ('posted', 'Posted'), ('Completed', 'Completed'), ('refunded', 'Refunded'), ('stale', 'Stale')], default='awaiting_payment', max_length=20),
        ),
    ]
