# Generated by Django 4.1.6 on 2023-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Comment',
            field=models.TextField(default=None, max_length=400),
        ),
    ]
