# Generated by Django 4.1.6 on 2023-03-02 14:39

from django.db import migrations, models
import django.db.models.deletion
import iranian_cities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0005_auto_20221004_0004'),
        ('store', '0027_alter_orderitem_price_alter_product_discount_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', iranian_cities.fields.ProvinceField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province')),
            ],
        ),
    ]
