# Generated by Django 4.1.6 on 2023-03-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0005_auto_20221004_0004'),
        ('store', '0028_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ostan', to='iranian_cities.province'),
        ),
    ]
