# Generated by Django 4.1.6 on 2023-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_address_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user_name',
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
