# Generated by Django 4.1.6 on 2023-03-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_address_is_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
