# Generated by Django 4.1.6 on 2023-03-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_product_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
