# Generated by Django 4.1.6 on 2023-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_address_address_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(),
        ),
    ]
