# Generated by Django 4.1.6 on 2023-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_shippingmethod_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default=None, max_length=100, verbose_name='Weight in pounds'),
        ),
    ]
