# Generated by Django 4.1.6 on 2023-03-10 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='توضیحات بیشتر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت لیر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True, verbose_name='قیمت اصلی لیر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(validators=[django.core.validators.RegexValidator(message='Not a valid URL', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')], verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(default=None, max_length=200, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default=None, max_length=100, verbose_name='وزن'),
        ),
    ]
