# Generated by Django 4.1.6 on 2023-03-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0005_auto_20221004_0004'),
        ('store', '0043_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=100, verbose_name='آدرس کامل'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_title',
            field=models.CharField(default=None, max_length=100, verbose_name=' آدرس عنوان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shahrestan', to='iranian_cities.county', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(default=None, max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='0', max_length=11, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ostan', to='iranian_cities.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=100, verbose_name='کد پستی'),
        ),
    ]
