"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
# master
# from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# master
# BASE_DIR = os.path.dirname(os.path.dirname(
#     os.path.dirname(os.path.abspath(__file__))))

# mode5
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# sharemun
# BASE_DIR = os.path.dirname(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mu3@%85&!#_vx6(&6selc^=iy(%(^e-a)y8#rl_he$22^7w137'
# mode5
# SECRET_KEY = 'z+ksf@)0d^qojbh4rnp4b1to$hq&*tt(3bs$gf(3i267g$k9ln'
# master
# SECRET_KEY = config('SECRET_KEY')
# shahremun
# SECRET_KEY = 'django-insecure-l7opb-9@7k2*kb)qa-zl%2twi&3zm5l+sa1hl(k4@5^rmu_f*t'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# master in other file .......


# ALLOWED_HOSTS = ['127.0.0.1']
ALLOWED_HOSTS = []
# master in other file .......



# LOGIN_REDIRECT_URL = '/'

# EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
# EMAIL_FILE_PATH = str(os.path.join(BASE_DIR, "sent_emails"))






INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store.apps.StoreConfig',
    'accounts.apps.AccountsConfig',
    'admin_comments',
    # 'mainapp', 
    'django_celery_results',
    'django_celery_beat',
    'send_mail_app',
    'crispy_forms',
    'iranian_cities',
    'django.contrib.humanize',
    'widget_tweaks',

    

#    'django_rename_app', 
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # master
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# master
# DEBUG_TOOLBAR_PANELS = [
#     'debug_toolbar.panels.versions.VersionsPanel',
#     'debug_toolbar.panels.timer.TimerPanel',
#     'debug_toolbar.panels.settings.SettingsPanel',
#     'debug_toolbar.panels.headers.HeadersPanel',
#     'debug_toolbar.panels.request.RequestPanel',
#     'debug_toolbar.panels.sql.SQLPanel',
#     'debug_toolbar.panels.staticfiles.StaticFilesPanel',
#     'debug_toolbar.panels.templates.TemplatesPanel',
#     'debug_toolbar.panels.cache.CachePanel',
#     'debug_toolbar.panels.signals.SignalsPanel',
#     'debug_toolbar.panels.logging.LoggingPanel',
#     'debug_toolbar.panels.redirects.RedirectsPanel',
    
# ]


# master
# def show_toolbar(request):
#     return True
# DEBUG_TOOLBAR_CONFIG = {
#     'INTERCEPT_REDIRECTS': False,
#     'SHOW_TOOLBAR_CALLBACK': show_toolbar
# }



ROOT_URLCONF = 'ecommerce.urls'
# master
# ROOT_URLCONF = 'djecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        # master
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        # sharemun
        # 'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart'
                # in shahremun
                # 'orders.context_processors.cart'
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'
# WSGI_APPLICATION = 'djecommerce.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'NAME': str(os.path.join(BASE_DIR, "db.sqlite3"))
        # in shahremun
        # 'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# in master in other files'....


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#  master 
# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.ModelBackend',
#     'allauth.account.auth_backends.AuthenticationBackend'
# )







# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

#mode5
# USE_L10N = True

#master
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

#mode5
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static')
#     # in shahremun 
#     BASE_DIR / 'static'
# ]

# master
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static_in_env')]
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')


# in shahremun 
# STATICFILES_DIRS = [
#     BASE_DIR / 'static'
# ]




# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]


#mode5
# MEDIA_URL = '/images/'f
# MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')

#master
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_root')

# sharemun
# BASE_DIR = os.path.dirname(os.path.dirname(__file__))
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/')
# MEDIA_URL = '/media/'


#master
# SITE_ID = 1
# LOGIN_REDIRECT_URL = '/'
# CRISPY_TEMPLATE_PACK = 'bootstrap4'

# master
# STRIPE_PUBLIC_KEY = config('STRIPE_TEST_PUBLIC_KEY')
# STRIPE_SECRET_KEY = config('STRIPE_TEST_SECRET_KEY')

# in shahremun توجه موثع استفاده از لاگین زاد 
AUTH_USER_MODEL = 'accounts.User'



DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = '43ebc7d9-3d6c-4ced-beeb-61bb6152fa5c'
AWS_SECRET_ACCESS_KEY = 'd278aca9edc9befb9a44747410fe1707492e2268'
AWS_S3_ENDPOINT_URL = 'https://shahremun-shop.s3.ir-tbz-sh1.arvanstorage.com'
AWS_STORAGE_BUCKET_NAME = 'shahremun-shop'
AWS_SERVICE_NAME = 's3'
AWS_S3_FILE_OVERWRITE = False



#SMTP CONFIGURATION

# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'leilamottagi@gmail.com'
# EMAIL_HOST_PASSWORD = 'vwigtdmxjfrwrorl'
# DEFAULT_FROM_EMAIL = 'leila'
# # EMAIL_HOST_USER = os.environ.get('User_Email')
# # EMAIL_HOST_PASSWORD = os.environ.get('User_Password')




# Sendinblue
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp-relay.sendinblue.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'leila_sendinblue'
EMAIL_HOST_PASSWORD = 'xsmtpsib-2921fd683afd99fee23d1f6df525f17c0202874c11ce8768b49e3b50b8b715e1-j6hwEnH98DR72zT3'



PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
)



ADMIN_COMMENTS_SHOW_EMPTY = True
ADMIN_COMMENTS_FORM_CLASS = "admin_comments.forms.CommentInlineForm"
ADMIN_COMMENTS_FORMSET_CLASS = "admin_comments.forms.CommentInlineFormset"




# CELERY SETTINGS

CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tehran'
# TIME_ZONE = 'Asia/Tehran'

CELERY_RESULT_BACKEND = 'django-db'

# #CELERY BEAT
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# SMTP Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
# EMAIL_HOST = 'smtp-relay.sendinblue.com'
EMAIL_PORT = 587
EMAIL_HOST_USER ='leilamottagi@gmail.com'
# EMAIL_HOST_USER = 'leila_sendinblue'
EMAIL_HOST_PASSWORD = "qqaxvokdgjlmghux"
# EMAIL_HOST_PASSWORD = 'xsmtpsib-2921fd683afd99fee23d1f6df525f17c0202874c11ce8768b49e3b50b8b715e1-j6hwEnH98DR72zT3'
DEFAULT_FROM_EMAIL = 'Celery <leila_sendinblue@gmail.com>'















# اجرای سلری::::::::::::
# (env) D:\django\shahremun_djcommerce_inTesting>celery -A ecommerce.celery worker --pool=solo -l info  

# (env) D:\django\shahremun_djcommerce_inTesting>celery -A ecommerce worker -l info

# اجرای سلری بیت 
# (env) D:\django\shahremun_djcommerce_inTesting>celery -A ecommerce beat -l INFO

# برای پریودیک تسک های ایجاد شده در دیتابیس دستی
# (env) D:\django\shahremun_djcommerce_inTesting>celery -A ecommerce beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler